version: '2'
services:
  web:
    build: .
    env_file: .env
    volumes:
      - .:/webapp
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
